@startuml
title Koordinationslogik

'cla
class Koordination {
  + match(hg: Hilfsgesuch, angebote: List<Hilfsangebot>): List<Zuordnung>
  + sendeBestätigung(z: Zuordnung): String
  + aktualisiereVorOrt(hg: Hilfsgesuch): void
}


class Hverwalten {
  + sendeAblehnung(z: Zuordnung): String
}

class Zuordnung {
  - hilfsgesuch: Hilfsgesuch
  - hilfsangebot: Hilfsangebot
}




Koordination --> Zuordnung : erstellt >
Hverwalten --> Zuordnung : prüft >
Zuordnung --> Hilfsangebot : verwendet >
Zuordnung --> Hilfsgesuch : verwendet >
@enduml
